Repository apache/skywalking-ui, pull requests merged in 2018-04, with the labels that each got.

#154 fix Field 'name' in type 'AppServerInfo' is undefined error in javascript
  src/models/application.js
  src/routes/Server/Server.js
Labels: enhancement

#156 Fix trace field start time error
  src/components/TraceTable/index.js
Labels: bug

#159 upload PostgreSQL icon
  public/img/node/POSTGRESQL.png
Labels: bug

#162 Icons Add License
  public/font/iconfont/iconfont.svg
Labels: document
