Repository apache/skywalking-ui, pull requests merged in 2018-03, with the labels that each got.

#122 Fix/resources
  mock/application.js
  mock/server.js
  src/components/Page/Search/index.js
  src/components/Topology/AppTopology.js
  src/components/TraceTable/index.js
  src/routes/Server/Server.js
Labels: bug

#123 Update git ignore
  .gitignore
Labels: bug

#124 Add new service dependency map
  mock/service.js
  src/components/Charts/Sankey/index.js
  src/components/Charts/equal.js
  src/components/Charts/index.js
  src/routes/Service/Service.js
Labels: enhancement

#125 Fix ignore for main repo
  .gitignore
Labels: bug

#126 Fix/bugs
  mock/application.js
  mock/server.js
  mock/service.js
  mock/topology.js
  mock/trace.js
  src/components/Charts/Area/index.js
  src/components/Charts/Sankey/index.js
  src/components/Topology/AppTopology.js
  src/components/TraceStack/index.js
  src/routes/Server/Server.js
  src/routes/Service/Service.js
Labels: bug

#128 Fix/e2e
  mock/server.js
  mock/trace.js
  public/alert.svg
  public/database.svg
  public/img/icon/alert.png
  public/img/icon/app.jpg
  public/img/icon/app.svg
  public/img/icon/data.png
  public/img/icon/database.png
  public/img/icon/favicon.png
  public/img/icon/mq.png
  public/img/icon/service.svg
  public/img/node/FEIGNDEFAULTHTTP.png
  public/img/node/NUTZHTTP.png
  public/img/node/NUTZMVC.png
  public/img/node/ORACLE.png
  public/img/node/TOMCAT.png
  public/redis.svg
  src/components/Topology/AppTopology.js
  src/components/Topology/ServiceTopology.js
  src/components/TraceTable/index.js
  src/models/trace.js
  src/routes/Dashboard/Dashboard.js
  src/routes/Server/Server.js
  src/routes/Trace/Trace.js
Labels: bug

#129 Update docs for 5.0.0
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  README.zh-CN.md
  package.json
Labels: document

#143 Fix bugs in e2e test
  mock/server.js
  mock/service.js
  public/favicon.png
  src/components/Page/Search/index.js
  src/models/trace.js
  src/routes/Application/Application.js
  src/routes/Dashboard/Dashboard.js
  src/routes/Server/Server.js
  src/routes/Service/Service.js
  src/routes/Trace/Trace.js
  src/utils/models.js
  src/utils/utils.js
Labels: bug

#144 Enhancement components
  src/components/Duration/Icon/index.js
  src/components/GlobalHeader/index.js
  src/components/Topology/AppTopology.js
  src/components/Topology/Base.js
  src/components/Topology/conf.js
  src/layouts/BasicLayout.js
  src/models/global.js
  src/utils/models.js
Labels: enhancement

#145 Update copyright
  src/layouts/BasicLayout.js
Labels: bug

#147 Bug of e2e test
  package-lock.json
  package.json
  src/index.js
  src/routes/Dashboard/Dashboard.js
  src/routes/Topology/Topology.js
  src/routes/Trace/Trace.js
  src/utils/models.js
  src/utils/request.js
Labels: bug

#148 Fix license issues
  public/css/iconfont.css
  public/css/iconfont.eot
  public/css/iconfont.js
  public/css/iconfont.svg
  public/css/iconfont.ttf
  public/css/iconfont.woff
  public/img/icon/app.png
  public/img/icon/app.svg
  public/img/icon/service.png
  public/img/icon/service.svg
  src/common/menu.js
  src/components/Charts/ChartCard/index.less
  src/components/Charts/Field/index.less
  src/components/Charts/Pie/index.less
  src/components/SiderMenu/SiderMenu.js
  src/index.ejs
  src/routes/Dashboard/Dashboard.js
Labels: Module/Global, bug

#152 Remove unnecessary files
  .ga
  .localized
  mock/.gitkeep
Labels: enhancement
