Repository apache/skywalking-ui, pull requests merged in 2018-12, with the labels that each got.

#205 Add Service instance SLA chart
  package-lock.json
  src/components/ServiceInstanceLitePanel/index.js
  src/models/service.js
  src/routes/Service/Service.js
  src/routes/Service/ServiceInstance.js
Labels: Module/Service, enhancement

#207 Fix #206
  mock/aggregation.js
  src/components/Page/Search/index.js
  src/models/endpoint.js
  src/routes/Endpoint/Endpoint.js
Labels: Module/Global, bug

#210 Feature: 'Update the span display'
  package.json
  src/components/TraceStack/index.js
  src/components/TraceTree/d3-trace.js
  src/components/TraceTree/index.js
  src/components/TraceTree/style.less
Labels: enhancement

#215 Feature: update spans display
  .webpackrc.js
  src/components/TraceTree/d3-trace.js
  src/components/TraceTree/index.js
  src/components/TraceTree/style.less
Labels: enhancement
