Repository apache/skywalking-ui, pull requests merged in 2019-02, with the labels that each got.

#226 Images ref from our Apache website.
  README.md
Labels: document

#231 fix monitor service page layout issue
  src/components/Charts/ChartCard/index.less
Labels: enhancement

#233 Feature: Add serviceInstance Search Support
  .roadhogrc.mock.js
  mock/trace.js
  src/models/trace.js
  src/routes/Trace/TraceSearch.js
Labels: Module/Trace

#235 Fix: fix bug #2276
  src/routes/Topology/Topology.js
Labels: bug
